site_name: Tree Explorer
repo_url: https://github.com/jhcepas/stv/tree/minimalist/
nav:
    - Home: index.md
    - Overview: overview.md
    - Essentials: essentials.md
    - API: api.md
    - Detailed Layout: detailed_layout.md
    - About: about.md
